# Generated by Django 6.1.1 on 2026-09-21 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Eleve",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=80)),
                ("prenom", models.CharField(max_length=80)),
                ("classe", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("reference_attestation", models.CharField(max_length=40, unique=True)),
                ("quotient_categorie", models.CharField(max_length=10)),
            ],
            options={
                "verbose_name": "élève",
                "ordering": ["nom", "prenom"],
            },
        ),
        migrations.CreateModel(
            name="Tarif",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quotient_categorie", models.CharField(max_length=10)),
                ("prix", models.PositiveIntegerField()),
                ("date_debut", models.DateField()),
                ("date_fin", models.DateField(blank=True, null=True)),
            ],
            options={
                "ordering": ["quotient_categorie", "-date_debut"],
            },
        ),
        migrations.CreateModel(
            name="Compte",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("solde", models.IntegerField(default=0)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ELEVE", "Élève"),
                            ("PERSONNEL", "Personnel"),
                            ("GESTIONNAIRE", "Gestionnaire"),
                        ],
                        default="ELEVE",
                        max_length=15,
                    ),
                ),
                (
                    "eleve",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restauration.eleve",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type_repas",
                    models.CharField(
                        choices=[("DEJEUNER", "Déjeuner"), ("DINER", "Dîner")],
                        default="DEJEUNER",
                        max_length=15,
                    ),
                ),
                ("capacite_max", models.PositiveIntegerField()),
                ("heure_limite", models.DateTimeField()),
            ],
            options={
                "ordering": ["date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("date", "type_repas"), name="service_unique_par_jour"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[("CONFIRMEE", "Confirmée"), ("ANNULEE", "Annulée")],
                        default="CONFIRMEE",
                        max_length=12,
                    ),
                ),
                ("prix", models.IntegerField()),
                ("date_reservation", models.DateTimeField(auto_now_add=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="restauration.eleve",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="restauration.service",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_reservation"],
            },
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("entree", models.CharField(blank=True, max_length=120)),
                ("plat", models.CharField(max_length=120)),
                ("dessert", models.CharField(blank=True, max_length=120)),
                (
                    "service",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu",
                        to="restauration.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("CREDIT", "Crédit"), ("DEBIT", "Débit")], max_length=6
                    ),
                ),
                ("montant", models.PositiveIntegerField()),
                (
                    "moyen",
                    models.CharField(
                        choices=[
                            ("DEBIT_RESA", "Débit sur réservation"),
                            ("CB", "Carte bancaire"),
                            ("ESPECES", "Espèces"),
                        ],
                        max_length=15,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "compte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="restauration.compte",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="restauration.reservation",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("statut", "CONFIRMEE")),
                fields=("eleve", "service"),
                name="une_resa_confirmee_par_service",
            ),
        ),
    ]
